/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminPanel;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Car;
import model.CarDetailsList;

/**
 *
 * @@author shreya
 */
public class CreateCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarPanel
     */
    private JPanel workPanel;
    CarDetailsList carDetailsList;

    public CreateCarPanel(JPanel workPanel, CarDetailsList carDetailsList) {
        initComponents();
        this.workPanel = workPanel;
        this.carDetailsList = carDetailsList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblModelName = new javax.swing.JLabel();
        txtModelName = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblMaintanenceCertificate = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtManufactureYear = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        btnSubmitButton = new javax.swing.JButton();
        checkAvailability = new javax.swing.JCheckBox();
        checkMaintanenceCertificate = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(102, 204, 255));
        setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Car");

        lblModelName.setBackground(new java.awt.Color(204, 204, 204));
        lblModelName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblModelName.setText("Model Name");

        txtModelName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblSerialNumber.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSerialNumber.setText("Serial Number");

        txtSerialNumber.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblManufacturer.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblManufacturer.setText("Manufacturer");

        lblMaintanenceCertificate.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblMaintanenceCertificate.setText("Maintanence Certificate");

        lblSeats.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSeats.setText("No of Seats");

        lblManufactureYear.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblManufactureYear.setText("Manufacture Year");

        lblLocation.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblLocation.setText("Location");

        txtManufacturer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtSeats.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtManufactureYear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtLocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblAvailability.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblAvailability.setText("Availability");

        btnSubmitButton.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSubmitButton.setText("Add ");
        btnSubmitButton.setMaximumSize(new java.awt.Dimension(100, 40));
        btnSubmitButton.setMinimumSize(new java.awt.Dimension(100, 30));
        btnSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitButtonActionPerformed(evt);
            }
        });

        checkAvailability.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        checkAvailability.setText("Available");

        checkMaintanenceCertificate.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        checkMaintanenceCertificate.setText("Expired");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblModelName)
                                    .addComponent(lblSerialNumber)
                                    .addComponent(lblManufacturer)
                                    .addComponent(lblSeats)
                                    .addComponent(lblManufactureYear)
                                    .addComponent(lblLocation))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(lblMaintanenceCertificate)
                                .addGap(18, 18, 18)
                                .addComponent(checkMaintanenceCertificate)
                                .addGap(93, 93, 93)
                                .addComponent(lblAvailability)
                                .addGap(18, 18, 18)
                                .addComponent(checkAvailability)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelName)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintanenceCertificate)
                    .addComponent(checkMaintanenceCertificate)
                    .addComponent(lblAvailability)
                    .addComponent(checkAvailability))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureYear)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(btnSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitButtonActionPerformed
        // TODO add your handling code here:

        //model name
        String model_name = txtModelName.getText();

        //serial no
        String serial_number = txtSerialNumber.getText();

        //manufacturer
        String manufacturer = txtManufacturer.getText();

        //seats
        int seats = 4;
        try {
            seats = Integer.parseInt(txtSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter valid number of seats");
        }

        //manufactur year
        int manufactureYear = 1980;
        try {
            if (txtManufactureYear.getText().trim().length() == 4) {
                manufactureYear = Integer.parseInt(txtManufactureYear.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid year");

        }

        //location
        String location = txtLocation.getText();
        
        //availability
        Boolean availability = checkAvailability.isSelected();
        
        //certi
        Boolean maintanenceCertificate = checkMaintanenceCertificate.isSelected();
        
        
        int initialSize = carDetailsList.getCarDetailsList().size();

        //null validation
        if (model_name.equals("") || serial_number.equals("") || manufacturer.equals("") || location.equals("") || seats == 0 || manufactureYear == 0) {
            JOptionPane.showMessageDialog(this, "Missing fields");
        } else {
            Car car = carDetailsList.addCar();
            car.setModelnumber(model_name);
            car.setManufacturer(manufacturer);
            car.setAvailability(availability);
            car.setLocation(location);
            car.setMaintanancecertificate(maintanenceCertificate);
            
            try {
                car.setManufactureyear(manufactureYear);
            } catch (NumberFormatException e) {
                carDetailsList.getCarDetailsList().remove(car);
                JOptionPane.showMessageDialog(null, "Enter Valid Year");
            }
            try {
                car.setSeats(seats);
            } catch (Exception e) {
                carDetailsList.getCarDetailsList().remove(car);
                JOptionPane.showMessageDialog(this, "Enter valid number of seats");

            }
            Set<String> serialNumberList = new HashSet<String>();
            for (Car cars: carDetailsList.getCarDetailsList()){
                serialNumberList.add(cars.getSerialnumber());
            }
            if (serialNumberList.contains(serial_number)){
                JOptionPane.showMessageDialog(this, "Enter unique Serial number");
                carDetailsList.getCarDetailsList().remove(car);
            }
            else{
                car.setSerialnumber(serial_number);
            }
            
            
                               
            
                if (initialSize < carDetailsList.getCarDetailsList().size()){
                    JOptionPane.showMessageDialog(this, "Car Added successfully");
                    
                    txtModelName.setText("");
                    txtSerialNumber.setText("");
                    txtManufacturer.setText("");
                    txtSeats.setText("");
                    txtManufactureYear.setText("");
                    txtLocation.setText("");
                    checkAvailability.setText("");
                    checkMaintanenceCertificate.setText("");
                    
         
                }
                      
        }


    }//GEN-LAST:event_btnSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitButton;
    private javax.swing.JCheckBox checkAvailability;
    private javax.swing.JCheckBox checkMaintanenceCertificate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMaintanenceCertificate;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
