/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminPanel;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.CarDetailsList;

/**
 *
 * @author shreya
 */
public class MainAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainAdminPanel
     */
    private JPanel workPanel;
    CarDetailsList carDetailsList;
    public MainAdminPanel(JPanel workPanel, CarDetailsList carDetailsList) {
        initComponents();
        this.workPanel = workPanel;
        this.carDetailsList = carDetailsList;
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdateDeleteCar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Admin");

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCreate.setText("Create Car ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdateDeleteCar.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateDeleteCar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnUpdateDeleteCar.setText("View Car ");
        btnUpdateDeleteCar.setActionCommand("View Car");
        btnUpdateDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeleteCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(434, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnUpdateDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateCarPanel createCar = new CreateCarPanel(workPanel, carDetailsList);
        workPanel.add("CreateCarPanel", createCar);
        CardLayout cardLayout = (CardLayout) workPanel.getLayout();
        cardLayout.next(workPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeleteCarActionPerformed
        // TODO add your handling code here:
        ViewAdminPanel viewPanel = new ViewAdminPanel(workPanel, carDetailsList);
        workPanel.add("ViewCarPanel", viewPanel);
        CardLayout cardLayout = (CardLayout) workPanel.getLayout();
        cardLayout.next(workPanel);
    }//GEN-LAST:event_btnUpdateDeleteCarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdateDeleteCar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
