/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminPanel;

import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarDetailsList;

/**
 *
 * @author shreya
 */
public class ViewAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminPanel
     */
    JPanel workPanel;
    CarDetailsList carDetailsList;
    public ViewAdminPanel(JPanel workPanel, CarDetailsList carDetailsList) {
        initComponents();
        this.workPanel = workPanel;
        this.carDetailsList = carDetailsList;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeleteCar = new javax.swing.JButton();
        lblAvailability = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        checkAvailability = new javax.swing.JCheckBox();
        checkMaintanenceCertificate = new javax.swing.JCheckBox();
        lblManufactureYear = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtManufactureYear = new javax.swing.JTextField();
        lblModelName = new javax.swing.JLabel();
        txtModelName = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblMaintanenceCertificate = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        lblFleetUpdateTime = new javax.swing.JLabel();
        txtFleetUpdateTime = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 204, 255));

        lblViewCar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblViewCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCar.setText("View Car");

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Model Name", "Serial Number", "Manufacture Year", "Manufacturer", "Location", "Seats", "Available", "Cerificate Expired"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDeleteCar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDeleteCar.setText("Delete");
        btnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCarActionPerformed(evt);
            }
        });

        lblAvailability.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblAvailability.setText("Availability");

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdate.setText("Update Details");
        btnUpdate.setMaximumSize(new java.awt.Dimension(100, 40));
        btnUpdate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        checkAvailability.setText("Available");

        checkMaintanenceCertificate.setText("Expired");

        lblManufactureYear.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblManufactureYear.setText("Manufacture Year");

        lblLocation.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblLocation.setText("Location");

        txtManufacturer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtSeats.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtManufactureYear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblModelName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblModelName.setText("Model Name");

        txtModelName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblSerialNumber.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSerialNumber.setText("Serial Number");

        txtSerialNumber.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblManufacturer.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblManufacturer.setText("Manufacturer");

        lblMaintanenceCertificate.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblMaintanenceCertificate.setText("Maintanence Certificate");

        lblSeats.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSeats.setText("Seats");

        txtLocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblFleetUpdateTime.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblFleetUpdateTime.setText("Last Updated : ");

        txtFleetUpdateTime.setEditable(false);
        txtFleetUpdateTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblViewCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(lblFleetUpdateTime)
                .addGap(37, 37, 37)
                .addComponent(txtFleetUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(415, 415, 415))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerialNumber)
                            .addComponent(lblModelName)
                            .addComponent(lblManufacturer)
                            .addComponent(lblSeats)
                            .addComponent(lblManufactureYear)
                            .addComponent(lblLocation)
                            .addComponent(lblAvailability)
                            .addComponent(lblMaintanenceCertificate))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkMaintanenceCertificate)
                            .addComponent(checkAvailability))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblViewCar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFleetUpdateTime)
                    .addComponent(txtFleetUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelName)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeats))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureYear)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(checkAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMaintanenceCertificate)
                    .addComponent(lblMaintanenceCertificate))
                .addGap(37, 37, 37)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ArrayList<Car> list = new ArrayList<Car>();
        list = carDetailsList.getCarDetailsList();
        
        int selectedRowIndex = jTable1.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Row");}
        else if (txtModelName.getText().equals("") || txtSerialNumber.getText().equals("") || txtManufacturer.getText().equals("") || 
                txtLocation.getText().equals(""))
        {
                JOptionPane.showMessageDialog(this, "Field Value cannot be null");
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
            
            try{           
                selectedCar.setModelnumber(txtModelName.getText());
                selectedCar.setSerialnumber(txtSerialNumber.getText());
                selectedCar.setManufacturer(txtManufacturer.getText());
                selectedCar.setManufactureyear(Integer.parseInt(txtManufactureYear.getText()));
                selectedCar.setLocation(txtLocation.getText());
                selectedCar.setSeats(Integer.parseInt(txtSeats.getText()));
                
                if (checkAvailability.isSelected()){
                    selectedCar.setAvailability(true);
                }
                else{
                    selectedCar.setAvailability(false);
                }                
                if(checkMaintanenceCertificate.isSelected()){
                    selectedCar.setMaintanancecertificate(true);
                }
                else{
                    selectedCar.setMaintanancecertificate(false);
                }
                JOptionPane.showMessageDialog(this, "Car Detail updated");
            }   
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                
            } 
            populateTable();
        }
         
        
             

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCarActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Row");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
            
            carDetailsList.deleteCarDetails(selectedCar);
                        
            JOptionPane.showMessageDialog(this, "Car Entry deleted");
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteCarActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = jTable1.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Row");
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
            
            txtModelName.setText(selectedCar.getModelnumber());
            txtSerialNumber.setText(selectedCar.getSerialnumber());
            txtSeats.setText(String.valueOf(selectedCar.getSeats()));
            txtManufacturer.setText(selectedCar.getManufacturer());
            txtManufactureYear.setText(String.valueOf(selectedCar.getManufactureyear()));
            txtLocation.setText(selectedCar.getLocation());
            
            if (selectedCar.isAvailability()){
                checkAvailability.setSelected(true);
            }
            else{
                checkAvailability.setSelected(false);
            }
            
            if (selectedCar.isMaintanancecertificate()){
                checkMaintanenceCertificate.setSelected(true);
            }
            else{
                checkMaintanenceCertificate.setSelected(false);
            }
            
            
            
            
        
        }
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox checkAvailability;
    private javax.swing.JCheckBox checkMaintanenceCertificate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblFleetUpdateTime;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMaintanenceCertificate;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblViewCar;
    private javax.swing.JTextField txtFleetUpdateTime;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for ( Car car : carDetailsList.getCarDetailsList() ){
            Object[] row = new Object[8];
            row[0] = car;
            row[1] = car.getSerialnumber();
            row[2] = car.getManufactureyear();
            row[3] = car.getManufacturer();
            row[4] = car.getLocation();
            row[5] = car.getSeats();
            row[6] = car.isAvailability();
            row[7] = car.isMaintanancecertificate();
            
            model.addRow(row);
            
        
        }
        carDetailsList.setLastFleetUpdate(LocalDateTime.now());
        txtFleetUpdateTime.setText(String.valueOf(carDetailsList.getLastFleetUpdate())); 
        
    }
}
